// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.2")]
[assembly: AssemblyFileVersionAttribute("1.0.2")]
[assembly: AssemblyInformationalVersionAttribute("1.0.2 a072a2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.2";
        internal const System.String AssemblyFileVersion = "1.0.2";
        internal const System.String AssemblyInformationalVersion = "1.0.2 a072a2";
    }
}
